variables:
    POM_PATH: ./aircompany-master/Java/pom.xml
    REPORT_PATH: ./aircompany-master/Java/target/site/cobertura/

stages:
    - test
    - coverage

test-job:
    stage: test
    tags:
        - java8
        - maven
    script:
        - echo "Executing tests"
        - mvn -f $POM_PATH clean test


coverage-job:
    stage: coverage
    tags:
        - java8
        - maven
    script:
        - echo "Collecting coverage"
        - mvn -f $POM_PATH cobertura:cobertura
    needs:
        - "test-job"
    artifacts:
        reports:
            cobertura: $REPORT_PATH
