variables:
    POM_PATH: ./aircompany-master/Java/pom.xml

test:
    tags:
        - java8
        - maven
    script:
        - echo "Executing tests"
        - ls -l && ls ./aircompany-master/
        - mvn -f $POM_PATH clean test
