variables:
    POM_PATH: ./aircompany-master/Java/pom.xml
    REPORT_PATH: ./aircompany-master/Java/src/target/site/cobertura.xml

test:
    tags:
        - java8
        - maven
    script:
        - echo "Executing tests"
        - mvn -f $POM_PATH clean test


coverage:
    tags:
        - java8
        - maven
    script:
        - echo "Collecting coverage"
        - mvn -f $POM_PATH cobertura:cobertura
    needs:
        - "test"
    artifacts:
        reports:
            cobertura: $REPORT_PATH
