variables:
    CLEAN_CODE_POM_PATH: ./aircompany-master/Java/pom.xml
    CLEAN_CODE_REPORT_PATH: ./aircompany-master/Java/target/site/cobertura/coverage.xml
    WEBDRIVER_POM_PATH: ./webdriver-task/pom.xml

stages:
    - test
    - coverage

clean-code-test:
    stage: test
    tags:
        - java8
        - maven
    script:
        - echo "Executing tests"
        - mvn -f $CLEAN_CODE_POM_PATH clean test

clean-code-coverage:
    stage: coverage
    tags:
        - java8
        - maven
    script:
        - echo "Collecting coverage"
        - mvn -f $CLEAN_CODE_POM_PATH cobertura:cobertura
    needs:
        - "clean-code-test"
    artifacts:
        reports:
            cobertura: $CLEAN_CODE_REPORT_PATH
        paths:
            - ./aircompany-master/Java/target/site/cobertura
        expire_in: 1 days
